quarkus.http.port=8084

# https://es.quarkus.io/guides/datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=mysql123

quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3307/ms-productos?createDatabaseIfNotExist=true
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=true

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true